//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuppyCafeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pets
    {
        public int pets_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string pet_name { get; set; }
        public Nullable<int> age { get; set; }
    
        public virtual employees employees { get; set; }
    }
}
