//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuppyCafeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int products_id { get; set; }
        public Nullable<int> departmen_id { get; set; }
        public string product_name { get; set; }
        public string type_of_product { get; set; }
    
        public virtual departments departments { get; set; }
    }
}
